var counties = [
    "Abbeville",
    "Acadia",
    "Accomack",
    "Ada",
    "Adair",
    "Adams",
    "Addison",
    "Adjuntas",
    "Aguada",
    "Aguadilla",
    "Aguas Buenas",
    "Aibonito",
    "Aiken",
    "Aitkin",
    "Alachua",
    "Alamance",
    "Alameda",
    "Alamosa",
    "Albany",
    "Albemarle",
    "Alcona",
    "Alcorn",
    "Aleutians",
    "Alexander",
    "Alexandria",
    "Alfalfa",
    "Alger",
    "Allamakee",
    "Allegan",
    "Allegany",
    "Alleghany",
    "Allegheny",
    "Allen",
    "Allendale",
    "Alpena",
    "Alpine",
    "Amador",
    "Amelia",
    "Amherst",
    "Amite",
    "Anchorage",
    "Anderson",
    "Andrew",
    "Andrews",
    "Androscoggin",
    "Angelina",
    "Anne Arundel",
    "Anoka",
    "Anson",
    "Antelope",
    "Antrim",
    "Apache",
    "Appanoose",
    "Appling",
    "Appomattox",
    "Aransas",
    "Arapahoe",
    "Archer",
    "Archuleta",
    "Arecibo",
    "Arenac",
    "Arkansas",
    "Arlington",
    "Armstrong",
    "Aroostook",
    "Arroyo",
    "Arthur",
    "Ascension",
    "Ashe",
    "Ashland",
    "Ashley",
    "Ashtabula",
    "Asotin",
    "Assumption",
    "Atascosa",
    "Atchison",
    "Athens",
    "Atkinson",
    "Atlantic",
    "Atoka",
    "Attala",
    "Audrain",
    "Audubon",
    "Auglaize",
    "Augusta",
    "Aurora",
    "Austin",
    "Autauga",
    "Avery",
    "Avoyelles",
    "Añasco",
    "Baca",
    "Bacon",
    "Bailey",
    "Baker",
    "Baker Island",
    "Baldwin",
    "Ballard",
    "Baltimore",
    "Bamberg",
    "Bandera",
    "Banks",
    "Banner",
    "Bannock",
    "Baraga",
    "Barber",
    "Barbour",
    "Barceloneta",
    "Barnes",
    "Barnstable",
    "Barnwell",
    "Barranquitas",
    "Barren",
    "Barron",
    "Barrow",
    "Barry",
    "Bartholomew",
    "Barton",
    "Bartow",
    "Bastrop",
    "Bates",
    "Bath",
    "Baxter",
    "Bay",
    "Bayamón",
    "Bayfield",
    "Baylor",
    "Beadle",
    "Bear Lake",
    "Beaufort",
    "Beauregard",
    "Beaver",
    "Beaverhead",
    "Becker",
    "Beckham",
    "Bedford",
    "Bee",
    "Belknap",
    "Bell",
    "Belmont",
    "Beltrami",
    "Ben Hill",
    "Benewah",
    "Bennett",
    "Bennington",
    "Benson",
    "Bent",
    "Benton",
    "Benzie",
    "Bergen",
    "Berkeley",
    "Berks",
    "Berkshire",
    "Bernalillo",
    "Berrien",
    "Bertie",
    "Bethel",
    "Bexar",
    "Bibb",
    "Bienville",
    "Big Horn",
    "Big Stone",
    "Billings",
    "Bingham",
    "Black Hawk",
    "Blackford",
    "Bladen",
    "Blaine",
    "Blair",
    "Blanco",
    "Bland",
    "Bleckley",
    "Bledsoe",
    "Blount",
    "Blue Earth",
    "Boise",
    "Bolivar",
    "Bollinger",
    "Bon Homme",
    "Bond",
    "Bonner",
    "Bonneville",
    "Boone",
    "Borden",
    "Bosque",
    "Bossier",
    "Botetourt",
    "Bottineau",
    "Boulder",
    "Boundary",
    "Bourbon",
    "Bowie",
    "Bowman",
    "Box Butte",
    "Box Elder",
    "Boyd",
    "Boyle",
    "Bracken",
    "Bradford",
    "Bradley",
    "Branch",
    "Brantley",
    "Braxton",
    "Brazoria",
    "Brazos",
    "Breathitt",
    "Breckinridge",
    "Bremer",
    "Brevard",
    "Brewster",
    "Briscoe",
    "Bristol",
    "Bristol Bay",
    "Broadwater",
    "Bronx",
    "Brooke",
    "Brookings",
    "Brooks",
    "Broome",
    "Broomfield",
    "Broward",
    "Brown",
    "Brule",
    "Brunswick",
    "Bryan",
    "Buchanan",
    "Buckingham",
    "Bucks",
    "Buena Vista",
    "Buffalo",
    "Bullitt",
    "Bulloch",
    "Bullock",
    "Buncombe",
    "Bureau",
    "Burke",
    "Burleigh",
    "Burleson",
    "Burlington",
    "Burnet",
    "Burnett",
    "Burt",
    "Butler",
    "Butte",
    "Butts",
    "Cabarrus",
    "Cabell",
    "Cabo Rojo",
    "Cache",
    "Caddo",
    "Caguas",
    "Calaveras",
    "Calcasieu",
    "Caldwell",
    "Caledonia",
    "Calhoun",
    "Callahan",
    "Callaway",
    "Calloway",
    "Calumet",
    "Calvert",
    "Camas",
    "Cambria",
    "Camden",
    "Cameron",
    "Camp",
    "Campbell",
    "Camuy",
    "Canadian",
    "Candler",
    "Cannon",
    "Canyon",
    "Canóvanas",
    "Cape Girardeau",
    "Cape May",
    "Carbon",
    "Caribou",
    "Carlisle",
    "Carlton",
    "Carolina",
    "Caroline",
    "Carroll",
    "Carson",
    "Carson",
    "Carter",
    "Carteret",
    "Carver",
    "Cascade",
    "Casey",
    "Cass",
    "Cassia",
    "Castro",
    "Caswell",
    "Catahoula",
    "Catawba",
    "Cataño",
    "Catoosa",
    "Catron",
    "Cattaraugus",
    "Cavalier",
    "Cayey",
    "Cayuga",
    "Cecil",
    "Cedar",
    "Ceiba",
    "Centre",
    "Cerro Gordo",
    "Chaffee",
    "Chambers",
    "Champaign",
    "Chariton",
    "Charles",
    "Charles",
    "Charles Mix",
    "Charleston",
    "Charlevoix",
    "Charlotte",
    "Charlottesville",
    "Charlton",
    "Chase",
    "Chatham",
    "Chattahoochee",
    "Chattooga",
    "Chautauqua",
    "Chaves",
    "Cheatham",
    "Cheboygan",
    "Chelan",
    "Chemung",
    "Chenango",
    "Cherokee",
    "Cherry",
    "Chesapeake",
    "Cheshire",
    "Chester",
    "Chesterfield",
    "Cheyenne",
    "Chickasaw",
    "Chicot",
    "Childress",
    "Chilton",
    "Chippewa",
    "Chisago",
    "Chittenden",
    "Choctaw",
    "Chouteau",
    "Chowan",
    "Christian",
    "Churchill",
    "Ciales",
    "Cibola",
    "Cidra",
    "Cimarron",
    "Citrus",
    "Clackamas",
    "Claiborne",
    "Clallam",
    "Clare",
    "Clarendon",
    "Clarion",
    "Clark",
    "Clarke",
    "Clatsop",
    "Clay",
    "Clayton",
    "Clear Creek",
    "Clearfield",
    "Clearwater",
    "Cleburne",
    "Clermont",
    "Cleveland",
    "Clinch",
    "Clinton",
    "Cloud",
    "Coahoma",
    "Coal",
    "Coamo",
    "Cobb",
    "Cochise",
    "Cochran",
    "Cocke",
    "Coconino",
    "Codington",
    "Coffee",
    "Coffey",
    "Coke",
    "Colbert",
    "Cole",
    "Coleman",
    "Coles",
    "Colfax",
    "Colleton",
    "Collier",
    "Collin",
    "Collingsworth",
    "Colonial Heights",
    "Colorado",
    "Colquitt",
    "Columbia",
    "Columbiana",
    "Columbus",
    "Colusa",
    "Comal",
    "Comanche",
    "Comerío",
    "Concho",
    "Concordia",
    "Conecuh",
    "Conejos",
    "Contra Costa",
    "Converse",
    "Conway",
    "Cook",
    "Cooke",
    "Cooper",
    "Coos",
    "Coosa",
    "Copiah",
    "Corozal",
    "Corson",
    "Cortland",
    "Coryell",
    "Coshocton",
    "Costilla",
    "Cottle",
    "Cotton",
    "Cottonwood",
    "Covington",
    "Coweta",
    "Cowley",
    "Cowlitz",
    "Craig",
    "Craighead",
    "Crane",
    "Craven",
    "Crawford",
    "Creek",
    "Crenshaw",
    "Crisp",
    "Crittenden",
    "Crockett",
    "Crook",
    "Crosby",
    "Cross",
    "Crow Wing",
    "Crowley",
    "Culberson",
    "Culebra",
    "Cullman",
    "Culpeper",
    "Cumberland",
    "Cuming",
    "Currituck",
    "Curry",
    "Custer",
    "Cuyahoga",
    "Dade",
    "Daggett",
    "Dakota",
    "Dale",
    "Dallam",
    "Dallas",
    "Dane",
    "Daniels",
    "Danville",
    "Dare",
    "Darke",
    "Darlington",
    "Dauphin",
    "Davidson",
    "Davie",
    "Daviess",
    "Davis",
    "Davison",
    "Dawes",
    "Dawson",
    "Day",
    "De Baca",
    "De Soto",
    "De Witt",
    "DeKalb",
    "DeSoto",
    "DeWitt",
    "Deaf Smith",
    "Dearborn",
    "Decatur",
    "Deer Lodge",
    "Defiance",
    "Del Norte",
    "Delaware",
    "Delta",
    "Denali",
    "Dent",
    "Denton",
    "Denver",
    "Des Moines",
    "Deschutes",
    "Desha",
    "Deuel",
    "Dewey",
    "Dickens",
    "Dickenson",
    "Dickey",
    "Dickinson",
    "Dickson",
    "Dillingham",
    "Dillon",
    "Dimmit",
    "Dinwiddie",
    "Divide",
    "Dixie",
    "Dixon",
    "Doddridge",
    "Dodge",
    "Dolores",
    "Doniphan",
    "Donley",
    "Dooly",
    "Door",
    "Dorado",
    "Dorchester",
    "Dougherty",
    "Douglas",
    "Doña Ana",
    "Drew",
    "DuPage",
    "Dubois",
    "Dubuque",
    "Duchesne",
    "Dukes",
    "Dundy",
    "Dunklin",
    "Dunn",
    "Duplin",
    "Durham",
    "Dutchess",
    "Duval",
    "Dyer",
    "Eagle",
    "Early",
    "East Baton Rouge",
    "East Carroll",
    "East Feliciana",
    "Eastern",
    "Eastland",
    "Eaton",
    "Eau Claire",
    "Echols",
    "Ector",
    "Eddy",
    "Edgar",
    "Edgecombe",
    "Edgefield",
    "Edmonson",
    "Edmunds",
    "Edwards",
    "Effingham",
    "El Dorado",
    "El Paso",
    "Elbert",
    "Elk",
    "Elkhart",
    "Elko",
    "Elliott",
    "Ellis",
    "Ellsworth",
    "Elmore",
    "Emanuel",
    "Emery",
    "Emmet",
    "Emmons",
    "Emporia",
    "Erath",
    "Erie",
    "Escambia",
    "Esmeralda",
    "Essex",
    "Estill",
    "Etowah",
    "Eureka",
    "Evangeline",
    "Evans",
    "Fairbanks North Star",
    "Fairfax",
    "Fairfield",
    "Fajardo",
    "Fall River",
    "Fallon",
    "Falls",
    "Falls Church",
    "Fannin",
    "Faribault",
    "Faulk",
    "Faulkner",
    "Fauquier",
    "Fayette",
    "Fentress",
    "Fergus",
    "Ferry",
    "Fillmore",
    "Finney",
    "Fisher",
    "Flagler",
    "Flathead",
    "Fleming",
    "Florence",
    "Florida",
    "Floyd",
    "Fluvanna",
    "Foard",
    "Fond du Lac",
    "Ford",
    "Forest",
    "Forrest",
    "Forsyth",
    "Fort Bend",
    "Foster",
    "Fountain",
    "Franklin",
    "Frederick",
    "Fredericksburg",
    "Freeborn",
    "Freestone",
    "Fremont",
    "Fresno",
    "Frio",
    "Frontier",
    "Fulton",
    "Furnas",
    "Gadsden",
    "Gage",
    "Gaines",
    "Galax",
    "Gallatin",
    "Gallia",
    "Galveston",
    "Garden",
    "Garfield",
    "Garland",
    "Garrard",
    "Garrett",
    "Garvin",
    "Garza",
    "Gasconade",
    "Gaston",
    "Gates",
    "Geary",
    "Geauga",
    "Gem",
    "Genesee",
    "Geneva",
    "Gentry",
    "George",
    "Georgetown",
    "Gibson",
    "Gila",
    "Gilchrist",
    "Giles",
    "Gillespie",
    "Gilliam",
    "Gilmer",
    "Gilpin",
    "Glacier",
    "Glades",
    "Gladwin",
    "Glascock",
    "Glasscock",
    "Glenn",
    "Gloucester",
    "Glynn",
    "Gogebic",
    "Golden Valley",
    "Goliad",
    "Gonzales",
    "Goochland",
    "Goodhue",
    "Gooding",
    "Gordon",
    "Goshen",
    "Gosper",
    "Gove",
    "Grady",
    "Grafton",
    "Graham",
    "Grainger",
    "Grand",
    "Grand Forks",
    "Grand Isle",
    "Grand Traverse",
    "Granite",
    "Grant",
    "Granville",
    "Gratiot",
    "Graves",
    "Gray",
    "Grays Harbor",
    "Grayson",
    "Greeley",
    "Green",
    "Green Lake",
    "Greenbrier",
    "Greene",
    "Greenlee",
    "Greensville",
    "Greenup",
    "Greenville",
    "Greenwood",
    "Greer",
    "Gregg",
    "Gregory",
    "Grenada",
    "Griggs",
    "Grimes",
    "Grundy",
    "Guadalupe",
    "Guam",
    "Guayama",
    "Guayanilla",
    "Guaynabo",
    "Guernsey",
    "Guilford",
    "Gulf",
    "Gunnison",
    "Gurabo",
    "Guthrie",
    "Guánica",
    "Gwinnett",
    "Haakon",
    "Habersham",
    "Haines",
    "Hale",
    "Halifax",
    "Hall",
    "Hamblen",
    "Hamilton",
    "Hamlin",
    "Hampden",
    "Hampshire",
    "Hampton",
    "Hancock",
    "Hand",
    "Hanover",
    "Hansford",
    "Hanson",
    "Haralson",
    "Hardee",
    "Hardeman",
    "Hardin",
    "Harding",
    "Hardy",
    "Harford",
    "Harlan",
    "Harmon",
    "Harnett",
    "Harney",
    "Harper",
    "Harris",
    "Harrison",
    "Harrisonburg",
    "Hart",
    "Hartford",
    "Hartley",
    "Harvey",
    "Haskell",
    "Hatillo",
    "Hawaii",
    "Hawkins",
    "Hayes",
    "Hays",
    "Haywood",
    "Heard",
    "Hemphill",
    "Hempstead",
    "Henderson",
    "Hendricks",
    "Hendry",
    "Hennepin",
    "Henrico",
    "Henry",
    "Herkimer",
    "Hernando",
    "Hertford",
    "Hettinger",
    "Hickman",
    "Hickory",
    "Hidalgo",
    "Highland",
    "Highlands",
    "Hill",
    "Hillsborough",
    "Hillsdale",
    "Hinds",
    "Hinsdale",
    "Hitchcock",
    "Hocking",
    "Hockley",
    "Hodgeman",
    "Hoke",
    "Holmes",
    "Holt",
    "Honolulu",
    "Hood",
    "Hood River",
    "Hooker",
    "Hoonah–Angoon",
    "Hopewell",
    "Hopkins",
    "Hormigueros",
    "Horry",
    "Hot Spring",
    "Hot Springs",
    "Houghton",
    "Houston",
    "Howard",
    "Howell",
    "Howland Island",
    "Hubbard",
    "Hudson",
    "Hudspeth",
    "Huerfano",
    "Hughes",
    "Humacao",
    "Humboldt",
    "Humphreys",
    "Hunt",
    "Hunterdon",
    "Huntingdon",
    "Huntington",
    "Huron",
    "Hutchinson",
    "Hyde",
    "Iberia",
    "Iberville",
    "Ida",
    "Idaho",
    "Imperial",
    "Independence",
    "Indian River",
    "Indiana",
    "Ingham",
    "Inyo",
    "Ionia",
    "Iosco",
    "Iowa",
    "Iredell",
    "Irion",
    "Iron",
    "Iroquois",
    "Irwin",
    "Isabela",
    "Isabella",
    "Isanti",
    "Island",
    "Isle of Wight",
    "Issaquena",
    "Itasca",
    "Itawamba",
    "Izard",
    "Jack",
    "Jackson",
    "James",
    "Jarvis Island",
    "Jasper",
    "Jay",
    "Jayuya",
    "Jeff Davis",
    "Jefferson",
    "Jefferson Davis",
    "Jenkins",
    "Jennings",
    "Jerauld",
    "Jerome",
    "Jersey",
    "Jessamine",
    "Jewell",
    "Jim Hogg",
    "Jim Wells",
    "Jo Daviess",
    "Johnson",
    "Johnston",
    "Johnston Atoll",
    "Jones",
    "Josephine",
    "Juab",
    "Juana Díaz",
    "Judith Basin",
    "Juncos",
    "Juneau",
    "Juniata",
    "Kalamazoo",
    "Kalawao",
    "Kalkaska",
    "Kanabec",
    "Kanawha",
    "Kandiyohi",
    "Kane",
    "Kankakee",
    "Karnes",
    "Kauai",
    "Kaufman",
    "Kay",
    "Kearney",
    "Kearny",
    "Keith",
    "Kemper",
    "Kenai Peninsula",
    "Kendall",
    "Kenedy",
    "Kennebec",
    "Kenosha",
    "Kent",
    "Kenton",
    "Keokuk",
    "Kern",
    "Kerr",
    "Kershaw",
    "Ketchikan Gateway",
    "Kewaunee",
    "Keweenaw",
    "Keya Paha",
    "Kidder",
    "Kimball",
    "Kimble",
    "King",
    "King George",
    "King William",
    "King and Queen",
    "Kingfisher",
    "Kingman",
    "Kingman Reef",
    "Kings",
    "Kingsbury",
    "Kinney",
    "Kiowa",
    "Kit Carson",
    "Kitsap",
    "Kittitas",
    "Kittson",
    "Klamath",
    "Kleberg",
    "Klickitat",
    "Knott",
    "Knox",
    "Kodiak Island",
    "Koochiching",
    "Kootenai",
    "Kosciusko",
    "Kossuth",
    "Kusilvak",
    "La Crosse",
    "La Paz",
    "La Plata",
    "La Salle",
    "LaGrange",
    "LaMoure",
    "LaPorte",
    "LaRue",
    "LaSalle",
    "Labette",
    "Lac qui Parle",
    "Lackawanna",
    "Laclede",
    "Lafayette",
    "Lafourche",
    "Lajas",
    "Lake",
    "Lake and Peninsula",
    "Lake of the Woods",
    "Lamar",
    "Lamb",
    "Lamoille",
    "Lampasas",
    "Lancaster",
    "Lander",
    "Lane",
    "Langlade",
    "Lanier",
    "Lapeer",
    "Laramie",
    "Lares",
    "Larimer",
    "Las Animas",
    "Las Marías",
    "Las Piedras",
    "Lassen",
    "Latah",
    "Latimer",
    "Lauderdale",
    "Laurel",
    "Laurens",
    "Lavaca",
    "Lawrence",
    "Le Flore",
    "Le Sueur",
    "Lea",
    "Leake",
    "Leavenworth",
    "Lebanon",
    "Lee",
    "Leelanau",
    "Leflore",
    "Lehigh",
    "Lemhi",
    "Lenawee",
    "Lenoir",
    "Leon",
    "Leslie",
    "Letcher",
    "Levy",
    "Lewis",
    "Lewis and Clark",
    "Lexington",
    "Liberty",
    "Licking",
    "Limestone",
    "Lincoln",
    "Linn",
    "Lipscomb",
    "Litchfield",
    "Little River",
    "Live Oak",
    "Livingston",
    "Llano",
    "Logan",
    "Long",
    "Lonoke",
    "Lorain",
    "Los Alamos",
    "Los Angeles",
    "Loudon",
    "Loudoun",
    "Louisa",
    "Loup",
    "Love",
    "Loving",
    "Lowndes",
    "Loíza",
    "Lubbock",
    "Lucas",
    "Luce",
    "Lumpkin",
    "Luna",
    "Lunenburg",
    "Luquillo",
    "Luzerne",
    "Lycoming",
    "Lyman",
    "Lynchburg",
    "Lynn",
    "Lyon",
    "Mackinac",
    "Macomb",
    "Macon",
    "Macoupin",
    "Madera",
    "Madison",
    "Magoffin",
    "Mahaska",
    "Mahnomen",
    "Mahoning",
    "Major",
    "Malheur",
    "Manassas",
    "Manassas Park",
    "Manatee",
    "Manatí",
    "Manistee",
    "Manitowoc",
    "Manu'a",
    "Marathon",
    "Marengo",
    "Maricao",
    "Maricopa",
    "Maries",
    "Marin",
    "Marinette",
    "Marion",
    "Mariposa",
    "Marlboro",
    "Marquette",
    "Marshall",
    "Martin",
    "Martinsville",
    "Mason",
    "Massac",
    "Matagorda",
    "Matanuska-Susitna",
    "Mathews",
    "Maui",
    "Maunabo",
    "Maury",
    "Maverick",
    "Mayagüez",
    "Mayes",
    "McClain",
    "McCone",
    "McCook",
    "McCormick",
    "McCracken",
    "McCreary",
    "McCulloch",
    "McCurtain",
    "McDonald",
    "McDonough",
    "McDowell",
    "McDuffie",
    "McHenry",
    "McIntosh",
    "McKean",
    "McKenzie",
    "McKinley",
    "McLean",
    "McLennan",
    "McLeod",
    "McMinn",
    "McMullen",
    "McNairy",
    "McPherson",
    "Meade",
    "Meagher",
    "Mecklenburg",
    "Mecosta",
    "Medina",
    "Meeker",
    "Meigs",
    "Mellette",
    "Menard",
    "Mendocino",
    "Menifee",
    "Menominee",
    "Merced",
    "Mercer",
    "Meriwether",
    "Merrick",
    "Merrimack",
    "Mesa",
    "Metcalfe",
    "Miami",
    "Miami-Dade",
    "Middlesex",
    "Midland",
    "Midway Islands",
    "Mifflin",
    "Milam",
    "Millard",
    "Mille Lacs",
    "Miller",
    "Mills",
    "Milwaukee",
    "Miner",
    "Mineral",
    "Mingo",
    "Minidoka",
    "Minnehaha",
    "Missaukee",
    "Mississippi",
    "Missoula",
    "Mitchell",
    "Mobile",
    "Moca",
    "Modoc",
    "Moffat",
    "Mohave",
    "Moniteau",
    "Monmouth",
    "Mono",
    "Monona",
    "Monongalia",
    "Monroe",
    "Montague",
    "Montcalm",
    "Monterey",
    "Montezuma",
    "Montgomery",
    "Montmorency",
    "Montour",
    "Montrose",
    "Moody",
    "Moore",
    "Mora",
    "Morehouse",
    "Morgan",
    "Morovis",
    "Morrill",
    "Morris",
    "Morrison",
    "Morrow",
    "Morton",
    "Motley",
    "Moultrie",
    "Mountrail",
    "Mower",
    "Muhlenberg",
    "Multnomah",
    "Murray",
    "Muscatine",
    "Muscogee",
    "Muskegon",
    "Muskingum",
    "Muskogee",
    "Musselshell",
    "Nacogdoches",
    "Naguabo",
    "Nance",
    "Nantucket",
    "Napa",
    "Naranjito",
    "Nash",
    "Nassau",
    "Natchitoches",
    "Natrona",
    "Navajo",
    "Navarro",
    "Navassa Island",
    "Nelson",
    "Nemaha",
    "Neosho",
    "Neshoba",
    "Ness",
    "Nevada",
    "New Castle",
    "New Hanover",
    "New Haven",
    "New Kent",
    "New London",
    "New Madrid",
    "New York",
    "Newaygo",
    "Newberry",
    "Newport",
    "Newport News",
    "Newton",
    "Nez Perce",
    "Niagara",
    "Nicholas",
    "Nicollet",
    "Niobrara",
    "Noble",
    "Nobles",
    "Nodaway",
    "Nolan",
    "Nome",
    "Norfolk",
    "Norman",
    "North Slope",
    "Northampton",
    "Northern Islands",
    "Northumberland",
    "Northwest Arctic",
    "Norton",
    "Nottoway",
    "Nowata",
    "Noxubee",
    "Nuckolls",
    "Nueces",
    "Nye",
    "O'Brien",
    "Oakland",
    "Obion",
    "Ocean",
    "Oceana",
    "Ochiltree",
    "Oconee",
    "Oconto",
    "Ogemaw",
    "Oglala Lakota",
    "Ogle",
    "Oglethorpe",
    "Ohio",
    "Okaloosa",
    "Okanogan",
    "Okeechobee",
    "Okfuskee",
    "Oklahoma",
    "Okmulgee",
    "Oktibbeha",
    "Oldham",
    "Oliver",
    "Olmsted",
    "Oneida",
    "Onondaga",
    "Onslow",
    "Ontario",
    "Ontonagon",
    "Orange",
    "Orangeburg",
    "Oregon",
    "Orleans",
    "Orocovis",
    "Osage",
    "Osborne",
    "Osceola",
    "Oscoda",
    "Oswego",
    "Otero",
    "Otoe",
    "Otsego",
    "Ottawa",
    "Otter Tail",
    "Ouachita",
    "Ouray",
    "Outagamie",
    "Overton",
    "Owen",
    "Owsley",
    "Owyhee",
    "Oxford",
    "Ozark",
    "Ozaukee",
    "Pacific",
    "Page",
    "Palm Beach",
    "Palmyra Atoll",
    "Palo Alto",
    "Palo Pinto",
    "Pamlico",
    "Panola",
    "Park",
    "Parke",
    "Parker",
    "Parmer",
    "Pasco",
    "Pasquotank",
    "Passaic",
    "Patillas",
    "Patrick",
    "Paulding",
    "Pawnee",
    "Payette",
    "Payne",
    "Peach",
    "Pearl River",
    "Pecos",
    "Pembina",
    "Pemiscot",
    "Pend Oreille",
    "Pender",
    "Pendleton",
    "Pennington",
    "Penobscot",
    "Peoria",
    "Pepin",
    "Perkins",
    "Perquimans",
    "Perry",
    "Pershing",
    "Person",
    "Petersburg",
    "Petroleum",
    "Pettis",
    "Peñuelas",
    "Phelps",
    "Philadelphia",
    "Phillips",
    "Piatt",
    "Pickaway",
    "Pickens",
    "Pickett",
    "Pierce",
    "Pike",
    "Pima",
    "Pinal",
    "Pine",
    "Pinellas",
    "Pipestone",
    "Piscataquis",
    "Pitkin",
    "Pitt",
    "Pittsburg",
    "Pittsylvania",
    "Piute",
    "Placer",
    "Plaquemines",
    "Platte",
    "Pleasants",
    "Plumas",
    "Plymouth",
    "Pocahontas",
    "Poinsett",
    "Pointe Coupee",
    "Polk",
    "Ponce",
    "Pondera",
    "Pontotoc",
    "Pope",
    "Poquoson",
    "Portage",
    "Porter",
    "Portsmouth",
    "Posey",
    "Pottawatomie",
    "Pottawattamie",
    "Potter",
    "Powder River",
    "Powell",
    "Power",
    "Poweshiek",
    "Powhatan",
    "Prairie",
    "Pratt",
    "Preble",
    "Prentiss",
    "Presidio",
    "Presque Isle",
    "Preston",
    "Price",
    "Prince Edward",
    "Prince George",
    "Prince George's",
    "Prince William",
    "Prince of Wales – Hyder",
    "Providence",
    "Prowers",
    "Pueblo",
    "Pulaski",
    "Pushmataha",
    "Putnam",
    "Quay",
    "Quebradillas",
    "Queen Anne's",
    "Queens",
    "Quitman",
    "Rabun",
    "Racine",
    "Radford",
    "Rains",
    "Raleigh",
    "Ralls",
    "Ramsey",
    "Randall",
    "Randolph",
    "Rankin",
    "Ransom",
    "Rapides",
    "Rappahannock",
    "Ravalli",
    "Rawlins",
    "Ray",
    "Reagan",
    "Real",
    "Red Lake",
    "Red River",
    "Red Willow",
    "Redwood",
    "Reeves",
    "Refugio",
    "Reno",
    "Rensselaer",
    "Renville",
    "Republic",
    "Reynolds",
    "Rhea",
    "Rice",
    "Rich",
    "Richardson",
    "Richland",
    "Richmond",
    "Riley",
    "Rincón",
    "Ringgold",
    "Rio Arriba",
    "Rio Blanco",
    "Rio Grande",
    "Ripley",
    "Ritchie",
    "Riverside",
    "Roane",
    "Roanoke",
    "Roberts",
    "Robertson",
    "Robeson",
    "Rock",
    "Rock Island",
    "Rockbridge",
    "Rockcastle",
    "Rockdale",
    "Rockingham",
    "Rockland",
    "Rockwall",
    "Roger Mills",
    "Rogers",
    "Rolette",
    "Rooks",
    "Roosevelt",
    "Roscommon",
    "Rose Atoll",
    "Roseau",
    "Rosebud",
    "Ross",
    "Rota",
    "Routt",
    "Rowan",
    "Runnels",
    "Rush",
    "Rusk",
    "Russell",
    "Rutherford",
    "Rutland",
    "Río Grande",
    "Sabana Grande",
    "Sabine",
    "Sac",
    "Sacramento",
    "Sagadahoc",
    "Saginaw",
    "Saguache",
    "Saint Croix Island",
    "Saint John Island",
    "Saint Thomas Island",
    "Saipan",
    "Salem",
    "Salinas",
    "Saline",
    "Salt Lake",
    "Saluda",
    "Sampson",
    "San Augustine",
    "San Benito",
    "San Bernardino",
    "San Diego",
    "San Francisco",
    "San Germán",
    "San Jacinto",
    "San Joaquin",
    "San Juan",
    "San Lorenzo",
    "San Luis Obispo",
    "San Mateo",
    "San Miguel",
    "San Patricio",
    "San Saba",
    "San Sebastián",
    "Sanborn",
    "Sanders",
    "Sandoval",
    "Sandusky",
    "Sangamon",
    "Sanilac",
    "Sanpete",
    "Santa Barbara",
    "Santa Clara",
    "Santa Cruz",
    "Santa Fe",
    "Santa Isabel",
    "Santa Rosa",
    "Sarasota",
    "Saratoga",
    "Sargent",
    "Sarpy",
    "Sauk",
    "Saunders",
    "Sawyer",
    "Schenectady",
    "Schleicher",
    "Schley",
    "Schoharie",
    "Schoolcraft",
    "Schuyler",
    "Schuylkill",
    "Scioto",
    "Scotland",
    "Scott",
    "Scotts Bluff",
    "Screven",
    "Scurry",
    "Searcy",
    "Sebastian",
    "Sedgwick",
    "Seminole",
    "Seneca",
    "Sequatchie",
    "Sequoyah",
    "Sevier",
    "Seward",
    "Shackelford",
    "Shannon",
    "Sharkey",
    "Sharp",
    "Shasta",
    "Shawano",
    "Shawnee",
    "Sheboygan",
    "Shelby",
    "Shenandoah",
    "Sherburne",
    "Sheridan",
    "Sherman",
    "Shiawassee",
    "Shoshone",
    "Sibley",
    "Sierra",
    "Silver Bow",
    "Simpson",
    "Sioux",
    "Siskiyou",
    "Sitka",
    "Skagit",
    "Skagway",
    "Skamania",
    "Slope",
    "Smith",
    "Smyth",
    "Snohomish",
    "Snyder",
    "Socorro",
    "Solano",
    "Somerset",
    "Somervell",
    "Sonoma",
    "Southampton",
    "Southeast Fairbanks",
    "Spalding",
    "Spartanburg",
    "Spencer",
    "Spink",
    "Spokane",
    "Spotsylvania",
    "St. Bernard",
    "St. Charles",
    "St. Clair",
    "St. Croix",
    "St. Francis",
    "St. Francois",
    "St. Helena",
    "St. James",
    "St. John the Baptist",
    "St. Johns",
    "St. Joseph",
    "St. Landry",
    "St. Lawrence",
    "St. Louis",
    "St. Lucie",
    "St. Martin",
    "St. Mary",
    "St. Mary's",
    "St. Tammany",
    "Stafford",
    "Stanislaus",
    "Stanley",
    "Stanly",
    "Stanton",
    "Stark",
    "Starke",
    "Starr",
    "Staunton",
    "Ste. Genevieve",
    "Stearns",
    "Steele",
    "Stephens",
    "Stephenson",
    "Sterling",
    "Steuben",
    "Stevens",
    "Stewart",
    "Stillwater",
    "Stoddard",
    "Stokes",
    "Stone",
    "Stonewall",
    "Storey",
    "Story",
    "Strafford",
    "Stutsman",
    "Sublette",
    "Suffolk",
    "Sullivan",
    "Sully",
    "Summers",
    "Summit",
    "Sumner",
    "Sumter",
    "Sunflower",
    "Surry",
    "Susquehanna",
    "Sussex",
    "Sutter",
    "Sutton",
    "Suwannee",
    "Swain",
    "Swains Island",
    "Sweet Grass",
    "Sweetwater",
    "Swift",
    "Swisher",
    "Switzerland",
    "Talbot",
    "Taliaferro",
    "Talladega",
    "Tallahatchie",
    "Tallapoosa",
    "Tama",
    "Taney",
    "Tangipahoa",
    "Taos",
    "Tarrant",
    "Tate",
    "Tattnall",
    "Taylor",
    "Tazewell",
    "Tehama",
    "Telfair",
    "Teller",
    "Tensas",
    "Terrebonne",
    "Terrell",
    "Terry",
    "Teton",
    "Texas",
    "Thayer",
    "Thomas",
    "Throckmorton",
    "Thurston",
    "Tift",
    "Tillamook",
    "Tillman",
    "Tinian",
    "Tioga",
    "Tippah",
    "Tippecanoe",
    "Tipton",
    "Tishomingo",
    "Titus",
    "Toa Alta",
    "Toa Baja",
    "Todd",
    "Tolland",
    "Tom Green",
    "Tompkins",
    "Tooele",
    "Toole",
    "Toombs",
    "Torrance",
    "Towner",
    "Towns",
    "Traill",
    "Transylvania",
    "Traverse",
    "Travis",
    "Treasure",
    "Trego",
    "Trempealeau",
    "Treutlen",
    "Trigg",
    "Trimble",
    "Trinity",
    "Tripp",
    "Troup",
    "Trousdale",
    "Trujillo Alto",
    "Trumbull",
    "Tucker",
    "Tulare",
    "Tulsa",
    "Tunica",
    "Tuolumne",
    "Turner",
    "Tuscaloosa",
    "Tuscarawas",
    "Tuscola",
    "Twiggs",
    "Twin Falls",
    "Tyler",
    "Tyrrell",
    "Uinta",
    "Uintah",
    "Ulster",
    "Umatilla",
    "Unicoi",
    "Union",
    "Upshur",
    "Upson",
    "Upton",
    "Utah",
    "Utuado",
    "Uvalde",
    "Val Verde",
    "Valdez–Cordova",
    "Valencia",
    "Valley",
    "Van Buren",
    "Van Wert",
    "Van Zandt",
    "Vance",
    "Vanderburgh",
    "Vega Alta",
    "Vega Baja",
    "Venango",
    "Ventura",
    "Vermilion",
    "Vermillion",
    "Vernon",
    "Victoria",
    "Vieques",
    "Vigo",
    "Vilas",
    "Villalba",
    "Vinton",
    "Virginia Beach",
    "Volusia",
    "Wabash",
    "Wabasha",
    "Wabaunsee",
    "Wadena",
    "Wagoner",
    "Wahkiakum",
    "Wake",
    "Wake Island",
    "Wakulla",
    "Waldo",
    "Walker",
    "Walla Walla",
    "Wallace",
    "Waller",
    "Wallowa",
    "Walsh",
    "Walthall",
    "Walton",
    "Walworth",
    "Wapello",
    "Ward",
    "Ware",
    "Warren",
    "Warrick",
    "Wasatch",
    "Wasco",
    "Waseca",
    "Washakie",
    "Washburn",
    "Washington",
    "Washita",
    "Washoe",
    "Washtenaw",
    "Watauga",
    "Watonwan",
    "Waukesha",
    "Waupaca",
    "Waushara",
    "Wayne",
    "Waynesboro",
    "Weakley",
    "Webb",
    "Weber",
    "Webster",
    "Weld",
    "Wells",
    "West Baton Rouge",
    "West Carroll",
    "West Feliciana",
    "Westchester",
    "Western District",
    "Westmoreland",
    "Weston",
    "Wetzel",
    "Wexford",
    "Wharton",
    "Whatcom",
    "Wheatland",
    "Wheeler",
    "White",
    "White Pine",
    "Whiteside",
    "Whitfield",
    "Whitley",
    "Whitman",
    "Wibaux",
    "Wichita",
    "Wicomico",
    "Wilbarger",
    "Wilcox",
    "Wilkes",
    "Wilkin",
    "Wilkinson",
    "Will",
    "Willacy",
    "Williams",
    "Williamsburg",
    "Williamson",
    "Wilson",
    "Winchester",
    "Windham",
    "Windsor",
    "Winkler",
    "Winn",
    "Winnebago",
    "Winneshiek",
    "Winona",
    "Winston",
    "Wirt",
    "Wise",
    "Wolfe",
    "Wood",
    "Woodbury",
    "Woodford",
    "Woodruff",
    "Woods",
    "Woodson",
    "Woodward",
    "Worcester",
    "Worth",
    "Wrangell",
    "Wright",
    "Wyandot",
    "Wyandotte",
    "Wyoming",
    "Wythe",
    "Yabucoa",
    "Yadkin",
    "Yakima",
    "Yakutat",
    "Yalobusha",
    "Yamhill",
    "Yancey",
    "Yankton",
    "Yates",
    "Yauco",
    "Yavapai",
    "Yazoo",
    "Yell",
    "Yellow Medicine",
    "Yellowstone",
    "Yoakum",
    "Yolo",
    "York",
    "Young",
    "Yuba",
    "Yukon–Koyukuk",
    "Yuma",
    "Zapata",
    "Zavala",
    "Ziebach",
];
